# Day 3：NumPy
### 學習目標

了解 NumPy array 是什麼

熟悉：

    array()
    sum()
    mean()
    max()
    min()
    std() 標準差(複習 {:.2f})
    reshape(a, b) 重塑array排列 3x4 4x3 ...
    知道 NumPy array 與 list 的差異 (元素逐一相加 vs. 合併)

能利用 NumPy 進行簡單資料分析

### 先安裝：

In [ ]:
import sys
print(sys.executable)
!{sys.executable} -m pip install numpy

### 安裝後重新執行

In [4]:
import numpy as np

print(np.__version__)

2.5.0


# Part 1：建立 NumPy array
NumPy array 就像升級版的 list，可以讓電腦更快進行數值計算。

In [7]:
import numpy as np

numbers = np.array([1, 2, 3, 4, 5])

print(numbers)

print(type(numbers))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Part 2：sum()（20 分鐘）
sum() 可以計算總和。

In [8]:
scores = np.array([80, 90, 75, 88, 95])
print(scores.sum())


428


## 練習2

In [13]:
sales = np.array([100, 150, 120, 180])
print(sales.sum())

550


# Part 3：mean()（平均值）

In [10]:
print(scores.mean())

85.6


## 練習3

In [12]:
temperature = np.array([25, 27, 28, 26, 30])
print(temperature.mean())

27.2


# Part 4：max()、min()

In [14]:
scores = np.array([80, 90, 75, 88, 95])
print(scores.max())
print(scores.min())

95
75


## 練習4

In [15]:
height = np.array([165, 172, 180, 168, 175])
print(f"最高身高:{height.max()}")
print(f"最低身高:{height.min()}")

最高身高:180
最低身高:165


# Part 5：std()（標準差）
標準差代表資料的分散程度。

In [24]:
scores = np.array([80, 90, 75, 88, 95])
print(f"{scores.std():.2f}")

7.17


## 練習5

In [25]:
weight = np.array([60, 62, 58, 65, 61])
print(f"{weight.std():.2f}")

2.32


# Part 6：reshape()
reshape 可以改變資料形狀。

In [28]:
numbers = np.array([1,2,3,4,5,6])
print(numbers)
#變成2x3
print(numbers.reshape(2,3))
#變成3x2
print(numbers.reshape(3,2))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


## 練習6
reshape 成 3×4

reshape 成 4×3

In [31]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.reshape(3, 4))

print(arr.reshape(4, 3))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Part 7：NumPy array 和 list 的差別

In [35]:
#list: a+b 輸出是合併
a = [1,2,3]
b = [4,5,6]

print(a+b)

#Numpy: a+b 輸出是逐個元素相加
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a+b)

[1, 2, 3, 4, 5, 6]
[5 7 9]


## 練習7

In [36]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print( list1 + list2 )
print(arr1 + arr2)

print(list1*2)
print(arr1*2)

[1, 2, 3, 4, 5, 6]
[5 7 9]
[1, 2, 3, 1, 2, 3]
[2 4 6]


## Project 1：成績分析器 ★

In [39]:
scores = np.array([78,85,90,92,88,76,95])

print(f"平均分數:{scores.mean():.1f}\n最高分:{scores.max()}\n最低分:{scores.min()}\n總分:{scores.sum()}\n標準差:{scores.std():.1f}")

平均分數:86.3
最高分:95
最低分:76
總分:604
標準差:6.6


## Project 2：BMI 分析器 ★

In [ ]:
import numpy as np

height = np.array([170, 165, 180, 175])
weight = np.array([65, 55, 80, 70])

BMI = weight / (height/100)**2
print(BMI)

#小數點後兩位(法1)
print(np.round(BMI, 2)) 
#法2
#for x in BMI:
    #print(f"{x:.2f}")

print(f"平均 BMI:{BMI.mean():.2f}\n最高 BMI:{BMI.max():.2f}\n最低 BMI:{BMI.min():.2f}")



[22.49134948 20.2020202  24.69135802 22.85714286]
[22.49 20.2  24.69 22.86]
平均 BMI:22.56
最高 BMI:24.69
最低 BMI:20.20


## Project 3：一週氣溫分析 ★

In [50]:
tempt = np.array([30, 32, 29, 28, 33, 35, 31])

print(f"平均:{tempt.mean():.1f}")
print(f"最高:{tempt.max():.1f}")
print(f"最低:{tempt.min():.1f}")
print(f"標準差:{tempt.std():.1f}")

平均:31.1
最高:35.0
最低:28.0
標準差:2.2


## Project 4：公司銷售分析 ★★

In [53]:
sales = np.array([120,150,180,200,170,220,250])
print(f"總銷售:{sales.sum():.1f}\n平均銷售:{sales.mean():.1f}\n最高銷售:{sales.max()}\n最低銷售:{sales.min()}")

print(f"高於平均的銷售:{sales[sales > sales.mean()]}") #Boolean Indexing [篩選條件]

總銷售:1290.0
平均銷售:184.3
最高銷售:250
最低銷售:120
高於平均的銷售:[200 220 250]


### Boolean Indexing = 用 True / False 篩選資料。

import numpy as np

scores = np.array([78,85,92,60,55,88,95,70])

#哪些成績大於 80？
print (scores > 80)

得到:

[False  True  True False False  True  True False]

意思是：
| 分數 | >80?  |
| -- | ----- |
| 78 | False |
| 85 | True  |
| 92 | True  |
| 60 | False |
| 55 | False |
| 88 | True  |
| 95 | True  |
| 70 | False |

把剛剛的條件放進 []：

scores[scores > 80]

得到:

[85 92 88 95]


## Project 5：考試成績分析 ★★

In [56]:
scores = np.array([78,85,92,60,55,88,95,70])
print(f"全班平均:{scores.mean():.1f}")
print(f"不及格成績:{scores[scores < 60]}")
print(f"不及格人數:{len(scores[scores<60])}")

全班平均:77.9
不及格成績:[55]
不及格人數:1


## Project 6：找出高收入者 ★★★

In [60]:
salary = np.array([40000, 55000, 70000, 45000, 90000, 60000])

#找出收入 > 60000
print(f"高收入者：{salary[salary > 60000]}")
print(f"平均收入:{salary.mean():.0f}\n最高收入:{salary.max()}\n最低收入:{salary.min()}")


高收入者：[70000 90000]
平均收入:60000
最高收入:90000
最低收入:40000


## Project 7：股票價格分析 ★★★

In [65]:
stock = np.array([100, 105, 98, 110, 108, 115, 120])

print(f"平均價格:{stock.mean():.1f}\n最高價格:{stock.max()}\n最低價格:{stock.min()}\n價格波動:{stock.std():.1f}")
print(f"高於平均價格：{stock[stock>stock.mean()]}")

平均價格:108.0
最高價格:120
最低價格:98
價格波動:7.3
高於平均價格：[110 115 120]


## Project 8：矩陣製作器 ★★★

In [69]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(numbers.reshape(3,4))
print(numbers.reshape(4,3))
print(numbers.reshape(2,6))
print(numbers.reshape(6,2))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


## Project 9：班級身高分析 ★★★★

In [71]:
height = np.array([165,170,172,168,180,175,178,160,162,169])
print(f"平均身高:{height.mean()}\n最高身高:{height.max()}\n最低身高:{height.min()}\n標準差:{height.std():.1f}")
print(f"高於平均身高：{height[height>height.mean()]}")

平均身高:169.9
最高身高:180
最低身高:160
標準差:6.2
高於平均身高：[170 172 180 175 178]


## Project 10：每天步數分析 ★★★★

In [74]:
steps = np.array([5000,7000,8000,6000,10000,12000,9000])
print(f"總步數:{steps.sum()}\n平均步數:{steps.mean():.1f}\n最高步數:{steps.max()}\n最低步數:{steps.min()}")
print(f"超過8000步:{steps[steps>8000]}")

總步數:57000
平均步數:8142.9
最高步數:12000
最低步數:5000
超過8000步:[10000 12000  9000]


## Project 11：電商訂單分析 ★★★★★

In [76]:
orders = np.array([150,200,120,300,180,250,400,350])
print(f"總營收:{orders.sum()}\n平均訂單價格:{orders.mean():.1f}\n最高訂單:{orders.max()}\n最低訂單:{orders.min()}\n標準差:{orders.std():.1f}")
print(f"大於平均訂單金額:{orders[orders>orders.mean()]}")

總營收:1950
平均訂單價格:243.8
最高訂單:400
最低訂單:120
標準差:92.9
大於平均訂單金額:[300 250 400 350]


## Project 12：迷你 Data Scientist 專案 ★★★★★

In [79]:
sales = np.array([120,150,180,200,170,220,250])
print("===== Sales Report =====")
print(f"總銷售量:{sales.sum()}\n平均銷售量:{sales.mean():.1f}\n最高銷售量:{sales.max()}\n最低銷售量:{sales.min()}\n標準差:{sales.std():.1f}")
print(" ")
print(f"高於平均值:{sales[sales>sales.mean()]}")
print(" ")
print(f"低於平均值:{sales[sales<sales.mean()]}")
print(" ")
print(f"共有{len(sales[sales>sales.mean()])}天高於平均值")
print(f"共有{len(sales[sales<sales.mean()])}天低於平均值")

===== Sales Report =====
總銷售量:1290
平均銷售量:184.3
最高銷售量:250
最低銷售量:120
標準差:40.3
 
高於平均值:[200 220 250]
 
低於平均值:[120 150 180 170]
 
共有3天高於平均值
共有4天低於平均值


## Project 13：學生成績排行榜 ★★★★★

In [90]:
students = np.array([85,92,78,96,88,75,90])
print(f"90分以上:{students[students>90]}")

print(f"不及格:{students[students<60]}")

print(f"平均分數:{students.mean():.1f}")

print(f"標準差:{students.std():.1f}")

print(f"最高分:{students.max()}")
print(f"最低分:{students.min()}")

90分以上:[92 96]
不及格:[]
平均分數:86.3
標準差:7.0
最高分:96
最低分:75
